[package]
name = "zed-slash-sqlite"
version = "0.1.0"
edition = "2021"
# edition.workspace = true
# publish.workspace = true
# license = "Apache-2.0"

# [lints]
# #workspace = true

[lib]
path = "src/schema.rs"
crate-type = ["cdylib"]

[dependencies]
rusqlite = "0.33.0"
zed_extension_api = "0.2.0"
